### ISSUE TITLE
onbeforenext callback 

### ISSUE THREAD

**Issue by hasanmk52** [Alex1990/simple-step#1]
Hi .. I am using your plugin for my project. I want to validate my form data in the first step when user clicks on Next. I am using the onbeforenext callback for that. How can i prevent to go to the next step if validation fails? Currently it executes the code in the callback and by default forwards to the next step.
Thanks in advance.
Hasan

**Comment by Alex1990** [comment]
If the validation fails in the onbeforenext, you can set the `nextEnabled` of the Step instance to `false`. 

```js
var step = $(elem).step({
  onbeforenext: function () {
    // If the validation fails, then
    step.nextEnabled = false;
  }
});
```

See the source code https://github.com/Alex1990/simple-step/blob/master/src/step.js#L93-L94.

**Comment by Alex1990** [comment]
I do not maintain this project. So, I don't recommend you use it.

**Comment by hasanmk52** [comment]
Thanks for your help. That helped.
